### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by crizaqcri** [virtualsecureplatform/kvsp#6]
I have tried to build the kvsp project directly from sources and I've got the following error when trying to compile the c file:
2020/07/15 09:00:47 CAHP_RT not found at /home/cris/projects/kvsp/build/share/kvsp/cahp-rt

The build was done with success, I have tried also the build with docker, it has finished with success but still can not execute the compile. (Secret key generation, bootstrapping key generation was possible)

Running directly from archive didn't work:
/home/cris/projects/kvsp_v28/bin/clang: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
2020/07/15 08:58:42 exit status 127

What can I do to be able to run it? I am using Ubuntu 19.10 and without CUDA options.

**Comment by ushitora-anqou** [comment]
Thanks for the feedback. It seems that there are two reasons for the error:

- KVSP requires libtinfo5 to run Clang 9, so `sudo apt install libtinfo5` will fix the latter (`cannot open shared object file`) error.
- Please check the files in `build/share/kvsp/`, which should include some JSON and TOML files and `cahp-rt` directory. If they don't exist, the build actually failed. In fact, error messages in build are displayed in the middle of the log instead of the end, so it is very difficult to find them :(  Hopefully, installing libtinfo5 helps us build KVSP, so please give it another try. 

I hope this will help.

**Comment by crizaqcri** [comment]
Thank you, for your response, I have installed libtinfo5 and used the built version of the kvsp, and I was able to run the fib.c example with success!
